"""CodeStory - backend/images.py

Optional editorial illustrations for Story chapters, generated by a local
Ollama image model through its OpenAI-compatible images endpoint
(`POST /v1/images/generations`).

Image generation is strictly optional: nothing here is required for the Story
text, and a missing or failing image model only means a chapter shows a
textual fallback. The model name comes from settings (`image_model`, empty =
disabled). Everything stays local — prompts are built from chapter titles and
narratives, never raw secrets or file contents the model did not already see.
"""

from __future__ import annotations

import base64
import json
import urllib.error
import urllib.request

import ollama
import store

IMAGE_TIMEOUT = 300
IMAGE_SIZE = "1024x1024"

STYLE_GUIDE = (
    "Editorial magazine illustration, warm ivory parchment background, deep "
    "navy and muted blue accents, sophisticated technical-magazine art "
    "direction, clean flat shapes, no text, no words, no labels."
)

NOT_CONFIGURED = (
    "No image model is configured. Set one in Settings, e.g. pull an Ollama "
    "image model and enter its name, then retry."
)


def _model() -> str:
    return (store.load_settings().get("image_model") or "").strip()


def status() -> dict:
    """Report whether chapter illustrations can be generated."""
    model = _model()
    if not model:
        return {"configured": False, "model": "", "available": False, "error": NOT_CONFIGURED}
    ai = ollama.status()
    if not ai.get("connected"):
        return {
            "configured": True,
            "model": model,
            "available": False,
            "error": ai.get("error") or ollama.CONNECT_ERROR,
        }
    effective = model if ":" in model else model + ":latest"
    return {
        "configured": True,
        "model": model,
        "available": effective in ai.get("models", []),
        "error": None if effective in ai.get("models", []) else
        f"The model '{model}' is not installed. Run: ollama pull {model}",
    }


def chapter_prompt(record: dict, chapter: dict) -> str:
    """Build an editorial illustration prompt from grounded chapter text."""
    subject = (chapter.get("title") or "").strip()
    narrative = (chapter.get("narrative") or "").strip()
    if len(narrative) > 400:
        narrative = narrative[:400].rsplit(" ", 1)[0]
    return (
        f"{STYLE_GUIDE} Illustration for a story chapter about the software project "
        f"'{record.get('name', 'Untitled')}'. Chapter: {subject}. Scene: {narrative}"
    )


def generate(prompt: str, model: str | None = None, timeout: float = IMAGE_TIMEOUT) -> dict:
    """Generate one PNG illustration. Returns bytes or an error message."""
    chosen = model or _model()
    if not chosen:
        return {"ok": False, "model": chosen, "error": NOT_CONFIGURED}

    payload = json.dumps({
        "model": chosen,
        "prompt": prompt,
        "size": IMAGE_SIZE,
        "response_format": "b64_json",
    }).encode("utf-8")
    request = urllib.request.Request(
        f"{ollama._host()}/v1/images/generations",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            data = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as error:
        detail = ""
        try:
            detail = error.read().decode("utf-8", "replace")
        except OSError:
            pass
        return {"ok": False, "model": chosen, "error": f"Ollama HTTP {error.code}: {detail[:300]}"}
    except (urllib.error.URLError, OSError, ValueError) as error:
        return {
            "ok": False,
            "model": chosen,
            "error": ollama.CONNECT_ERROR if isinstance(error, urllib.error.URLError) else str(error),
        }

    items = data.get("data") or []
    encoded = items[0].get("b64_json") if items else None
    if not encoded:
        return {"ok": False, "model": chosen, "error": "The image model returned no image."}
    try:
        return {"ok": True, "model": chosen, "png": base64.b64decode(encoded)}
    except (ValueError, TypeError):
        return {"ok": False, "model": chosen, "error": "The image model returned invalid image data."}
